language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install opencv-contrib-python==4.0.1.23
  - pip install tensorflow==1.13.1
  - pip install coverage
script:
  - cd tests && coverage run --source=../vtk/ -m nose2
notifications:
  slack: 1701robocubs:7SLMoWn0v7ysfBEzmpheMEq9
